// <auto-generated />

using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace UserBehavior.Analytics.Api.Migrations.Application
{
    /// <inheritdoc />
    public partial class Add_Subscriptions : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "subscriptions",
                schema: "UserBehavior.Analytics",
                columns: table => new
                {
                    id = table.Column<string>(type: "character varying(500)", maxLength: 500, nullable: false),
                    customer_id = table.Column<string>(type: "character varying(500)", nullable: false),
                    subscription_type = table.Column<string>(type: "text", nullable: false),
                    monthly_fee = table.Column<decimal>(type: "numeric", nullable: false),
                    payment_method = table.Column<string>(type: "text", nullable: false),
                    account_age_months = table.Column<int>(type: "integer", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_subscriptions", x => x.id);
                    table.ForeignKey(
                        name: "fk_subscriptions_customers_customer_id",
                        column: x => x.customer_id,
                        principalSchema: "UserBehavior.Analytics",
                        principalTable: "customers",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "ix_subscriptions_customer_id",
                schema: "UserBehavior.Analytics",
                table: "subscriptions",
                column: "customer_id");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "subscriptions",
                schema: "UserBehavior.Analytics");
        }
    }
}
