// <auto-generated />

using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace UserBehavior.Analytics.Api.Migrations.Application
{
    /// <inheritdoc />
    public partial class Updated_Customer : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "external_customer_id",
                schema: "UserBehavior.Analytics",
                table: "customers");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "external_customer_id",
                schema: "UserBehavior.Analytics",
                table: "customers",
                type: "text",
                nullable: false,
                defaultValue: "");
        }
    }
}
