// <auto-generated />

using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace UserBehavior.Analytics.Api.Migrations.Application
{
    /// <inheritdoc />
    public partial class Add_CustomerChurn : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "customer_churn",
                schema: "UserBehavior.Analytics",
                columns: table => new
                {
                    id = table.Column<string>(type: "character varying(500)", maxLength: 500, nullable: false),
                    customer_id = table.Column<string>(type: "character varying(500)", nullable: false),
                    churned = table.Column<bool>(type: "boolean", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_customer_churn", x => x.id);
                    table.ForeignKey(
                        name: "fk_customer_churn_customers_customer_id",
                        column: x => x.customer_id,
                        principalSchema: "UserBehavior.Analytics",
                        principalTable: "customers",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "ix_customer_churn_customer_id",
                schema: "UserBehavior.Analytics",
                table: "customer_churn",
                column: "customer_id");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "customer_churn",
                schema: "UserBehavior.Analytics");
        }
    }
}
