// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UserBehavior.Analytics.Api.Database;

#nullable disable

namespace UserBehavior.Analytics.Api.Migrations.Application
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260331170239_Add_Subscriptions")]
    partial class Add_Subscriptions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("UserBehavior.Analytics")
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UserBehavior.Analytics.Api.Entities.Customer", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("id");

                    b.Property<int>("Age")
                        .HasColumnType("integer")
                        .HasColumnName("age");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("gender");

                    b.HasKey("Id")
                        .HasName("pk_customers");

                    b.ToTable("customers", "UserBehavior.Analytics");
                });

            modelBuilder.Entity("UserBehavior.Analytics.Api.Entities.Subscription", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("id");

                    b.Property<int>("AccountAgeMonths")
                        .HasColumnType("integer")
                        .HasColumnName("account_age_months");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("character varying(500)")
                        .HasColumnName("customer_id");

                    b.Property<decimal>("MonthlyFee")
                        .HasColumnType("numeric")
                        .HasColumnName("monthly_fee");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payment_method");

                    b.Property<string>("SubscriptionType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subscription_type");

                    b.HasKey("Id")
                        .HasName("pk_subscriptions");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_subscriptions_customer_id");

                    b.ToTable("subscriptions", "UserBehavior.Analytics");
                });

            modelBuilder.Entity("UserBehavior.Analytics.Api.Entities.Subscription", b =>
                {
                    b.HasOne("UserBehavior.Analytics.Api.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_subscriptions_customers_customer_id");

                    b.Navigation("Customer");
                });
#pragma warning restore 612, 618
        }
    }
}
