// <auto-generated />

using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace UserBehavior.Analytics.Api.Migrations.Application
{
    /// <inheritdoc />
    public partial class RenamedEngagementTable : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "fk_customer_engagements_customers_customer_id",
                schema: "UserBehavior.Analytics",
                table: "customer_engagements");

            migrationBuilder.DropPrimaryKey(
                name: "pk_customer_engagements",
                schema: "UserBehavior.Analytics",
                table: "customer_engagements");

            migrationBuilder.RenameTable(
                name: "customer_engagements",
                schema: "UserBehavior.Analytics",
                newName: "customer_engagement",
                newSchema: "UserBehavior.Analytics");

            migrationBuilder.RenameIndex(
                name: "ix_customer_engagements_customer_id",
                schema: "UserBehavior.Analytics",
                table: "customer_engagement",
                newName: "ix_customer_engagement_customer_id");

            migrationBuilder.AddPrimaryKey(
                name: "pk_customer_engagement",
                schema: "UserBehavior.Analytics",
                table: "customer_engagement",
                column: "id");

            migrationBuilder.AddForeignKey(
                name: "fk_customer_engagement_customers_customer_id",
                schema: "UserBehavior.Analytics",
                table: "customer_engagement",
                column: "customer_id",
                principalSchema: "UserBehavior.Analytics",
                principalTable: "customers",
                principalColumn: "id",
                onDelete: ReferentialAction.Cascade);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "fk_customer_engagement_customers_customer_id",
                schema: "UserBehavior.Analytics",
                table: "customer_engagement");

            migrationBuilder.DropPrimaryKey(
                name: "pk_customer_engagement",
                schema: "UserBehavior.Analytics",
                table: "customer_engagement");

            migrationBuilder.RenameTable(
                name: "customer_engagement",
                schema: "UserBehavior.Analytics",
                newName: "customer_engagements",
                newSchema: "UserBehavior.Analytics");

            migrationBuilder.RenameIndex(
                name: "ix_customer_engagement_customer_id",
                schema: "UserBehavior.Analytics",
                table: "customer_engagements",
                newName: "ix_customer_engagements_customer_id");

            migrationBuilder.AddPrimaryKey(
                name: "pk_customer_engagements",
                schema: "UserBehavior.Analytics",
                table: "customer_engagements",
                column: "id");

            migrationBuilder.AddForeignKey(
                name: "fk_customer_engagements_customers_customer_id",
                schema: "UserBehavior.Analytics",
                table: "customer_engagements",
                column: "customer_id",
                principalSchema: "UserBehavior.Analytics",
                principalTable: "customers",
                principalColumn: "id",
                onDelete: ReferentialAction.Cascade);
        }
    }
}
